---
name: AnsibleCI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:

    permissions:
      contents: read
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - molecule_distro: 'rockylinux9'
            experimental: false
          - molecule_distro: 'rockylinux8'
            experimental: false
          - molecule_distro: 'ubuntu2204'
            experimental: false
          - molecule_distro: 'ubuntu2004'
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"
      ANSIBLE_ROLE: r_pufky.pihole

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-plugins docker ansible-lint flake8 testinfra ansible yamllint netaddr
          mkdir -p $HOME/.ansible/roles && ln -s $GITHUB_WORKSPACE/$ANSIBLE_ROLE $HOME/.ansible/roles/
      - name: Environment
        run: |
          set -x
          ansible --version
          ansible-config dump --only-changed -t all
          pwd
          env
          find . -ls
      - name: Galaxy dependencies
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-galaxy install --timeout 120 --verbose -r molecule/default/requirements.yml
        continue-on-error: true
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
